name: Build, Scan, and Push to GAR

on:
  push:
    branches: [ main ]

jobs:
  security-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/python-3.11@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: --severity-threshold=high

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1

      - name: Configure Docker for GCP
        run: gcloud auth configure-docker us-central1-docker.pkg.dev

      - name: Build image
        run: docker build -t us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/python-gcp-repo/app:${{ github.sha }} .

      - name: Run Snyk container scan
        uses: snyk/actions/docker@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          image: us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/python-gcp-repo/app:${{ github.sha }}
          args: --severity-threshold=high

      - name: Push image
        run: docker push us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/python-gcp-repo/app:${{ github.sha }}